import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import PropTypes from 'prop-types';
import { get } from 'lodash';
import Header from './Header';

function Layout({props}){
    const { children, header } = props

    return (
        <Fragment>
            <Header>

            </Header>
            <Header>
                <title>Evos FE William</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Header>
        </Fragment>

    )
}

Layout.defaultProps = {
    
};
  
Layout.propTypes = {
    children: PropTypes.element,
    headerChild: PropTypes.element,
};

export default Layout;

